### ISSUE TITLE
Individual Assignment Checklist

### ISSUE THREAD

**Issue by caesarw0** [caesarw0/Student_Living_Guide_Dash#1]
## Contents - Create a Dash app

- [x] Step 1 - Set up the assignment structure
- [x] Step 2 - Motivation and purpose
- [x] Step 3 - Description of your app
    - [x] Add a **usage** section in Readme
- [x] Step 4. Select the results you want to include in the dashboard in relation to your target audience.
- [x] Step 5. Choose how to present the information in the UI.
    - [x] at least two different reactive elements
    - [x] not reuse exactly the same plots, maps and tables from the milestone
- [x] Step 6: Code the app following a workflow.
    - [x] - A title.
    - [x] - Add a theme using the library dash_bootstrap_components.
    - [x] - Two reactive elements with their widgets.
    - [x] - Labels or subtitles to all the widgets.
    - [x] - If you have included plots or tables, make sure the axis are labeled properly ( don’t use the name of the dataset variable if not a label that anyone can understand), and the units are correct.
    - [x] - Check that the reactive elements are working properly (the element is reactive to the user selection) before submitting your app.
    - [x] - Include at least two layout (html.* or dbc.*) elements in the UI.
- [x] Step 7: mini - peer review activity
    - [x] - Write a short text explaining at least two pieces of constructive feedback and add it as a github issue in their repository.
- [x] Step 8: Prodution-grade app: ensure the reproducibility and deploy the app.
    - [x] - Add a LICENSE.
    - [x] - Deploy the app using Render and include the link on the GitHub repo where the user can find it easily (README.md or about section).
    - [x] - Add in the README.md a reference section to the dataset you use.
- [x] Step 9: Creating the app as an open-source project.
    - [x] - Add a CONTRIBUTING.md file.
    - [x] - Add a CODE_OF_CONDUCT.md file.

Submission
